# railway.toml – use pre-built image instead of DOCKERFILE
[build]
builder = "IMAGE"
image = "ghcr.io/fractalic-ai/fractalic:main"

[deploy]
startCommand = "supervisord -c /etc/supervisor/conf.d/supervisord.conf"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
port = 3000
[[services]]
name = "backend"
port = 8000
[[services]]
name = "ai-server"
port = 8001

[env]
NODE_ENV  = "production"
PYTHONPATH = "/app"
