services:
  - type: web
    runtime: image
    name: fractalic
    image:
      url: ghcr.io/fractalic-ai/fractalic:main
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHONPATH
        value: /app
    healthCheckPath: /
    scaling:
      minInstances: 1
      maxInstances: 1
