services:
  - type: web
    name: fractalic
    image: ghcr.io/fractalic-ai/fractalic:main   # <- no build
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHONPATH
        value: /app
    healthCheckPath: /
    scaling:
      minInstances: 1
      maxInstances: 1
