name: fractalic
services:
  - name: fractalic
    image:
      registry_type: ghcr
      registry: ghcr.io
      repository: fractalic-ai/fractalic
      tag: main           # <- dev tag
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: "production"
      - key: PYTHONPATH
        value: "/app"
