name: Test Package Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        echo "🔨 Building package for Python 3.11..."
        python -m build
    
    - name: Check package
      run: |
        echo "🔍 Checking package..."
        python -m twine check dist/*
    
    - name: Test installation
      run: |
        echo "🧪 Testing installation..."
        pip install dist/*.whl
        
        # Test CLI is available
        fractalic --help
        
        # Test Python import
        python -c "
        import fractalic
        print(f'✅ Fractalic {fractalic.__version__} imported successfully')
        print(f'Available functions: {[f for f in dir(fractalic) if not f.startswith(\"_\")]}')
        "
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-build-artifacts
        path: dist/
        retention-days: 7
